### ISSUE TITLE
My subscriptions list in grid layout is misaligned by a long shot

### ISSUE THREAD

**Issue by Bottomfard6127** [sapondanaisriwan/AdashimaaTube#31]
I have this issue for quite a while now, and maybe it will become more problematic in the long run since you've changed the menu options of subscriptions in grid layout into default. 
![bruh moment subscription](https://user-images.githubusercontent.com/126884197/222730563-a79479af-b663-4c69-b8e0-a1f05c67d2ac.png)

**Comment by Bottomfard6127** [comment]
Sorry I replied late, I am currently using firefox, i tested it on other browser same issue persists.

**Comment by sapondanaisriwan** [comment]
Can you try with another account?

**Comment by Bottomfard6127** [comment]
it works, kinda but the names are under the profile of the channel
![image](https://user-images.githubusercontent.com/126884197/222886426-d37a1040-760f-4b87-94ac-a28490efa13a.png)

**Comment by sapondanaisriwan** [comment]
I think the reason it's not working for you is because of the new UI update Youtube issue.

**Comment by sapondanaisriwan** [comment]
> it works, kinda but the names are under the profile of the channel ![image](https://user-images.githubusercontent.com/126884197/222886426-d37a1040-760f-4b87-94ac-a28490efa13a.png)

The channel name is too long I'll fix it in the update, anyway you can turn it off
![w5WeSpwO2n](https://user-images.githubusercontent.com/64634605/222890359-1a23c177-f362-4390-9217-e980049b1fdf.png)

**Comment by Bottomfard6127** [comment]
thanks for looking up on this, will wait for a fix, in the meantime I'll just turn off the grid layout

**Comment by sapondanaisriwan** [comment]
@Bottomfard6127 Are the bugs fixed in v2.0.2?

**Comment by Bottomfard6127** [comment]
hello sorry for the late reply its still not fixed sadly
![image](https://user-images.githubusercontent.com/126884197/224327205-8e60b689-fa1c-4879-9335-77506a37fb32.png)
btw I came to report also that there is also another bug where in the search results the profile is still at circular form even though I put it in zero value or square.
![image](https://user-images.githubusercontent.com/126884197/224327474-8520d1e5-8701-423c-b233-a30a0d68dae9.png)

**Comment by sapondanaisriwan** [comment]
Can you try to turn off other extensions that affect YouTube except AdashimaaTube?

**Comment by Bottomfard6127** [comment]
I did now and both the bugs are still present

**Comment by sapondanaisriwan** [comment]
what is this extension/script?
![msedge_lPJ1D8CIpZ](https://user-images.githubusercontent.com/64634605/224328843-80b228ab-3bfb-4399-8c79-22e636157de3.png)

**Comment by Bottomfard6127** [comment]
its this one
![image](https://user-images.githubusercontent.com/126884197/224329069-2c620d98-d0f1-4bb4-8d31-34d095169ab2.png)

I already turned it off as well as the other scripts but the bug still persist
![image](https://user-images.githubusercontent.com/126884197/224329229-f023efcb-b5c6-4bf2-b578-40bd404356ae.png)

![image](https://user-images.githubusercontent.com/126884197/224329323-ea535f0c-afa5-4f77-a55f-173d2c63dfcc.png)

**Comment by sapondanaisriwan** [comment]
Can you try with another account?

**Comment by Bottomfard6127** [comment]
sure thing be back in a second

**Comment by Bottomfard6127** [comment]
damn it works well with my other acc

**Comment by sapondanaisriwan** [comment]
I knew it LOL

**Comment by Bottomfard6127** [comment]
man youtube just love screwing with my main account

**Comment by Bottomfard6127** [comment]
any idea whats wrong with it?

**Comment by Bottomfard6127** [comment]
both the bugs are fixed in my other account by the way

**Comment by sapondanaisriwan** [comment]
I have no clue.

> any idea whats wrong with it?

**Comment by sapondanaisriwan** [comment]
I can't reproduce the bugs since it did not happen my account, but if you really want to fix it you can give me your account.

**Comment by Bottomfard6127** [comment]
no offense but I'll have to politely decline that for now, its not that major of a bug that will ruin my experience, I might though on bugs that just plainly ruins my youtube

**Comment by sapondanaisriwan** [comment]
It's ok btw I'll still open these issues and I want to know who else has been affected.

**Comment by Bottomfard6127** [comment]
Good idea, good luck out there imma go to sleep

**Comment by sapondanaisriwan** [comment]
> It's ok btw I'll still open these issues and I want to know who else has been affected.

Have a good sleep 😊

**Comment by Bottomfard6127** [comment]
Hello mate, back again with another bug report, so the option of removing the thanks, and clip button is kinda broken right now, when I click on a video supporting those options they still appear even though I have them on, they do disappear when I turn off and on the script but when I click out of the video and then rewatch, they appear again, even though I have them turned off, I haven't tested the other options of removing buttons or if this is a me problem too but I'll put it in here just in case
![image](https://user-images.githubusercontent.com/126884197/224985535-36a914f7-9c10-4926-8d6c-417f321d2699.png)

**Comment by sapondanaisriwan** [comment]
Can you create a new issue please.

**Comment by Bottomfard6127** [comment]
affirmative, sorry to dump it here mate wait a minute
